<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Summary extends Model
{
    protected $fillable = [
        'meeting_id',
        'original_text',
        'summary',
        'type',
        'metadata',
    ];

    protected $casts = [
        'metadata' => 'array',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];

    public function meeting(): BelongsTo
    {
        return $this->belongsTo(Meeting::class);
    }

    public function isAutoGenerated(): bool
    {
        return $this->type === 'auto';
    }

    public function isManualGenerated(): bool
    {
        return $this->type === 'manual';
    }
}
